In [1]:
import polars as pl
import yfinance as yf
import pandas as pd

In [2]:
df = pl.read_csv('results_endowus_A/AGG_decisions.csv')

FileNotFoundError: No such file or directory (os error 2): results_endowus_A/AGG_decisions.csv

In [ ]:
df

shape: (201, 2)
┌────────────┬─────────────────────────────────┐
│ test_date  ┆ decision                        │
│ ---        ┆ ---                             │
│ str        ┆ str                             │
╞════════════╪═════════════════════════════════╡
│ 2020-02-17 ┆ {"Target_Return_30d": "-1.8%",… │
│ 2020-02-03 ┆ {"Target_Return_30d": "-1.8%",… │
│ 2020-02-24 ┆ {"Target_Return_30d": "-1.5%",… │
│ 2020-03-02 ┆ {"Target_Return_30d": "-1.8%",… │
│ 2020-02-10 ┆ {"Target_Return_30d": "-1.8%",… │
│ …          ┆ …                               │
│ 2023-10-16 ┆ {"Target_Return_30d": "-1.5%",… │
│ 2023-09-25 ┆ {"Target_Return_30d": "-2.0%",… │
│ 2023-10-30 ┆ {"Target_Return_30d": "-1.5%",… │
│ 2023-10-23 ┆ {"Target_Return_30d": "+0.5%",… │
│ 2023-10-09 ┆ {"Target_Return_30d": "-1.5%",… │
└────────────┴─────────────────────────────────┘

In [3]:
def download_prices(tickers: list[str], start: str, end: str):
    print(f"Downloading prices for {len(tickers)} tickers …")
    raw = yf.download(
        tickers,
        start=start,
        end=end,
        auto_adjust=True,
        progress=False,
    )
    if isinstance(raw.columns, pd.MultiIndex):
        close_df = raw["Close"]
        open_df = raw["Open"]
    else:
        close_df = raw[["Close"]].rename(columns={"Close": tickers[0]})
        open_df = raw[["Open"]].rename(columns={"Open": tickers[0]})

    close_df.index = pd.to_datetime(close_df.index)
    open_df.index = pd.to_datetime(open_df.index)
    print(open_df)
    return close_df.sort_index().dropna(how="all"), open_df.sort_index().dropna(
        how="all"
    )

In [4]:
download_prices(["^990100-USD-STRD"], "2020-04-30", "2024-01-01")

Downloading prices for 1 tickers …
Ticker      ^990100-USD-STRD
Date
2020-04-30       2072.600098
2020-05-01       2049.800049
2020-05-04       2002.099976
2020-05-05       1998.199951
2020-05-06       2018.199951
...                      ...
2023-12-22       3146.899902
2023-12-26       3152.899902
2023-12-27       3165.600098
2023-12-28       3176.500000
2023-12-29       3174.199951

[922 rows x 1 columns]

(Ticker      ^990100-USD-STRD
 Date
 2020-04-30       2052.899902
 2020-05-01       2004.800049
 2020-05-04       1997.800049
 2020-05-05       2018.099976
 2020-05-06       2007.599976
 ...                      ...
 2023-12-22       3152.300049
 2023-12-26       3162.699951
 2023-12-27       3175.699951
 2023-12-28       3178.100098
 2023-12-29       3169.199951

 [922 rows x 1 columns],
 Ticker      ^990100-USD-STRD
 Date
 2020-04-30       2072.600098
 2020-05-01       2049.800049
 2020-05-04       2002.099976
 2020-05-05       1998.199951
 2020-05-06       2018.199951
 ...                      ...
 2023-12-22       3146.899902
 2023-12-26       3152.899902
 2023-12-27       3165.600098
 2023-12-28       3176.500000
 2023-12-29       3174.199951

 [922 rows x 1 columns])

In [ ]:
yf.Ticker("0P0001EF2T.SI").history(start="2020-04-30", end="2024-01-01")

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2020-04-30 00:00:00+08:00,18.340000,18.340000,18.340000,18.340000,0,0.0,0.0,0.0
2020-05-11 00:00:00+08:00,18.969999,18.969999,18.969999,18.969999,0,0.0,0.0,0.0
2020-05-12 00:00:00+08:00,18.750000,18.750000,18.750000,18.750000,0,0.0,0.0,0.0
2020-05-13 00:00:00+08:00,18.780001,18.780001,18.780001,18.780001,0,0.0,0.0,0.0
2020-05-14 00:00:00+08:00,18.700001,18.700001,18.700001,18.700001,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2023-12-21 00:00:00+08:00,23.150000,23.150000,23.150000,23.150000,0,0.0,0.0,0.0
2023-12-22 00:00:00+08:00,23.190001,23.190001,23.190001,23.190001,0,0.0,0.0,0.0
2023-12-27 00:00:00+08:00,23.389999,23.389999,23.389999,23.389999,0,0.0,0.0,0.0
2023-12-28 00:00:00+08:00,23.549999,23.549999,23.549999,23.549999,0,0.0,0.0,0.0
2023-12-29 00:00:00+08:00,23.610001,23.610001,23.610001,23.610001,0,0.0,0.0,0.0